apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-svc
  labels:
    svc: mongoexpress-svc
  namespace: mongo
spec:
  selector:
    pod: mongoexpress
  ports:
  - name: tcp
    port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 30000 #30000~32767
  type: LoadBalancer